### ISSUE TITLE
Not able to use with rollup config

### ISSUE THREAD

**Issue by aalavandhaann** [johh/three-gltf-loader#3] opened 2018-11-03 00:23 UTC
I am pretty sure the plugin works fine. I am trying to understand why I am not able to use any npm plugins related to threejs. Whenever I install a plugin for threejs (threejs examples) and use rollup for my project, it annoys me with the error

`(node-resolve plugin) Error: Could not resolve '/home/user/rollupwiththree/node_modules/three/build/three.module.js' from commonjs-proxy:/home/user/rollupwiththree/node_modules/three/build/three.module.js`

When I do the following imports in my code for es6 classes

```
import {EventDispatcher, JSONLoader, Color} from 'three';
import GLTFLoader from 'three-gltf-loader';
```

Any ideas what I am missing here? Something to add to my rollup.config.js?

Regards,

#0K

**Comment by johh** [comment] 2018-11-03 16:49
Hey there,
are you sure you have threejs installed properly?
Running `npm i --save three` should do the trick.
If that doesn't work, can you provide the entire repository? I'd be happy to look into it.

**Comment by aalavandhaann** [comment] 2018-11-03 17:09
I installed threejs using

`npm install three --save-dev`

You can view the repository at https://github.com/aalavandhaann/blueprint-js

The import statements for GLTFLoader can be found at 

src/scripts/model/scene.js at line `2` as `import {GLTFLoader} from 'three-gltf-loader';`


Regards,

#0K

**Comment by johh** [comment] 2018-11-04 19:42
Hm, I can't seem to get the build working on my machine, however, I've noticed a few things:

- `'three-gltf-loader'` only exports a default, so it should be imported as such i.e. `import GLTFLoader from 'three-gltf-loader';`
- the version of Rollup you're using is fairly old, but your rollup.config.js uses a the newer syntax which is only supported by newer versions of Rollup.

Maybe the issue is somehow related to one of those things.
I'm closing this issue for now, since it doesn't seem to be directly related to `three-gltf-loader`, but let me know if you figure it out. 😄

**Closed as completed by johh** 2018-11-04 19:42 UTC
Labels: question

**Comment by aalavandhaann** [comment] 2018-11-04 23:20
Hey many many thanks. You were absolutely, amazingly, perfectly right about the cause of the problem. Indeed the version of rollup I used was the real culprit. I am fairly new to the whole nodejs/npm ecosystem. Whenever I found good plugins that helps to implement the functionality of threejs examples, i had this annoying error of node_modules for three_modules. As per your advice I updated the rollup version and now it compiles with the same message as a warning than as an error. 

I am able to use your plugin to load GLTF files. Look at the url https://aalavandhaann.github.io/blueprint-js/build/ and click the '+' button to add an item to the scene. You should be able to see the infamous yellow duck, which is actually a GLTF model. You might need to scroll to the bottom of the items page to see it.

My many many thanks to your efforts and time in resolving this issue. Once again thanks to you for the plugin.

Regards,

#0K

**Comment by johh** [comment] 2018-11-07 19:10
Thanks man, glad I could help! 😄
